"""use numeric money fields

Revision ID: bdaaff8a2a5e
Revises: 9aa9e449328d
Create Date: 2026-07-31 18:27:13.735620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdaaff8a2a5e'
down_revision: Union[str, Sequence[str], None] = '9aa9e449328d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.add_column('positions', sa.Column('ticker', sa.String(), nullable=True))
    op.add_column('positions', sa.Column('asset_type', sa.String(), nullable=True))
    op.alter_column('positions', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('positions', 'market_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'market_value',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('positions', 'quantity',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('positions', 'asset_type')
    op.drop_column('positions', 'ticker')
    op.alter_column('accounts', 'balance',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
